language: python

os: linux

jobs:
  include:
    - python: "2.7"
      env: DEPS="numpy>=1.16"
    - python: "3.5"
      env: DEPS="numpy>=1.16 pytest>=6"
    - python: "3.6"
      env: DEPS="numpy>=1.16 pytest>=6"
    - python: "3.7"
      env: DEPS="numpy>=1.16 pytest>=6" COVERAGE=true
    - python: "3.8"
      env: DEPS="numpy>=1.16 pytest>=6"

cache: pip


# Have to install manually numpy>=1.16 for astropy
# Pip is not doing it
install:
  - pip install $DEPS
  - pip install .[test]
  - |
    if [[ $COVERAGE == true ]]; then
      pip install codeclimate-test-reporter coveralls;
    fi

script:
  - |
    if [[ $COVERAGE == true ]]; then
      coverage run --source fridadrp -m pytest
    else
      pytest -s -v fridadrp
    fi

after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
  - if [[ $COVERAGE == true ]]; then codeclimate-test-reporter; fi
