
version: 2
jobs:
  # using tox
  toxify36:
      docker:
        - image: python:3.6
      steps:
        - run: apt-get update
        - run: apt-get install python-dev
        - run: pip install tox
        - checkout
        - run: tox -e py36

workflows:
  version: 2
  fridadrp:
    jobs:
      - toxify36
