name: FRIDA
configurations:
  values:
    - c7f94f7d-1f57-4644-86d6-7004a2506680
  default: c7f94f7d-1f57-4644-86d6-7004a2506680
modes:
  - key: success
    name: Recipe Success
    summary: Test mode
    description: >
      Full description of the Test mode
  - key: test1
    name: Test1
    summary: Subtraction of two raw images
    description: >
      Full description of the test1 mode
  - key: test2
    name: Test2
    summary: Addition of sky and target frames and subtraction of result 
    description: >
      Full description of the test2 mode
pipelines:
  default:
    version: 1
    recipes:
      success: numina.core.utils.AlwaysSuccessRecipe
      test1: fridadrp.recipes.auxiliary.Test1Recipe
      test2: fridadrp.recipes.auxiliary.Test2Recipe
